# config example
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml
env:
  TERM: xterm-256color
  WINIT_HIDPI_FACTOR: "1"

window:
  dimensions:
    columns: 80
    lines: 24

  padding:
    x: 10
    y: 10

  dynamic_padding: false

  decorations: full

  startup_mode: Windowed

scrolling:
  history: 2500
  multiplier: 3
  auto_scroll: false

tabspaces: 4

font:
  normal:
    family: Noto Sans Mono
    style: Regular

  bold:
    family: Noto Sans Mono
    style: Bold

  italic:
    family: Noto Sans Mono
    style: Italic

  bold_italic:
    family: Noto Sans Mono
    style: Bold Italic

  size: 10

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

visual_bell:
  animation: EaseOutExpo
  duration: 0
  color: '0xffffff'

background_opacity: 0.5

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: false

dynamic_title: true

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: false

working_directory: None

alt_send_esc: true

debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false
  ref_test: false

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: false

  url:
    launcher:
      program: xdg-open

    modifiers: None

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

key_bindings:
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Add,      mods: Control,       action: IncreaseFontSize }
  - { key: Subtract, mods: Control,       action: DecreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: Return,   mods: Alt,           action: ToggleFullscreen }
  - { key: Paste,                         action: Paste            }
  - { key: Copy,                          action: Copy             }
  - { key: L,        mods: Control,       action: ClearLogNotice   }
  - { key: L,        mods: Control,       chars: "\x0c"            }
  - { key: PageUp,   mods: Shift,         action: ScrollPageUp,   mode: ~Alt }
  - { key: PageDown, mods: Shift,         action: ScrollPageDown, mode: ~Alt }
  - { key: Home,     mods: Shift,         action: ScrollToTop,    mode: ~Alt }
  - { key: End,      mods: Shift,         action: ScrollToBottom, mode: ~Alt }


draw_bold_text_with_bright_colors: true

# https://github.com/aaron-williamson/base16-alacritty/blob/master/colors/base16-classic-dark-256.yml
# Base16 Classic Dark 256 - alacritty color config
# Jason Heeris (http://heeris.id.au)
colors:
  # Default colors
  primary:
    background: '0x151515'
    foreground: '0xd0d0d0'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x151515'
    cursor: '0xd0d0d0'

  # Normal colors
  normal:
    black:   '0x151515'
    red:     '0xac4142'
    green:   '0x90a959'
    yellow:  '0xf4bf75'
    blue:    '0x6a9fb5'
    magenta: '0xaa759f'
    cyan:    '0x75b5aa'
    white:   '0xd0d0d0'

  # Bright colors
  bright:
    black:   '0x505050'
    red:     '0xac4142'
    green:   '0x90a959'
    yellow:  '0xf4bf75'
    blue:    '0x6a9fb5'
    magenta: '0xaa759f'
    cyan:    '0x75b5aa'
    white:   '0xf5f5f5'

  indexed_colors:
    - { index: 16, color: '0xd28445' }
    - { index: 17, color: '0x8f5536' }
    - { index: 18, color: '0x202020' }
    - { index: 19, color: '0x303030' }
    - { index: 20, color: '0xb0b0b0' }
    - { index: 21, color: '0xe0e0e0' }